title: Dr Nikos Mavrakis
description: Assistant Professor, Durham Space Research Centre, Department of Computer Science, Durham University, UK
logo: /assets/img/pic_mavrakis.jpg
remote_theme: jekyll/minima

plugins:
- jekyll-remote-theme 