title: Dr Nikos Mavrakis
description: Assistant Professor of Space Engineering, School of Metallurgy and Materials, University of Birmingham, UK
logo: /assets/img/pic_mavrakis.jpg
theme: jekyll-theme-minimal