title: Dr Nikos Mavrakis
description: Assistant Professor, Durham Space Research Centre, Department of Computer Science, Durham University, UK
logo: /assets/img/pic_mavrakis.jpg
remote_theme: pages-themes/minimal@v0.2.0

plugins:
- jekyll-remote-theme 